apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-client-provisioner
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{.Release.Name}}-provisioner-runner
rules:
- apiGroups: [""]
  resources: ["events","secrets","persistentvolumes","persistentvolumeclaims","pods", "nodes","services" , "deployment","replicasets"]
  verbs: ["get","patch", "watch", "list","create","update","deletecollection"]
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
  verbs:
    - list
    - watch
